package AdditionApp;


/**
* AdditionApp/Addition.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Addition.idl
* Friday, February 17, 2017 11:27:01 AM MMT
*/

public interface Addition extends AdditionOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Addition
