package HelloApp;


/**
* HelloApp/Hello.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from hello.idl
* Wednesday, August 17, 2016 6:39:51 PM PDT
*/

public interface Hello extends HelloOperations, 
org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Hello
