package HelloApp;


/**
* HelloApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from hello.idl
* Wednesday, August 17, 2016 6:39:51 PM PDT
*/

public interface HelloOperations 
{
  String sayHello ();
} // interface HelloOperations
